function writeSummary(path, modelName, mTrain, mVal, AUCtr, AUCval, posClass)
%WRITESUMMARY Write a human-readable metrics summary file.
    fid = fopen(path, 'w');
    fprintf(fid, 'METRICS SUMMARY - %s\n', modelName);
    fprintf(fid, 'Generated: %s\n\n', datestr(now));
    blk = @(tag,m,auc) fprintf(fid, ...
        ['[%s]\n  Accuracy           : %.4f\n  Macro Precision    : %.4f\n' ...
         '  Macro Recall       : %.4f\n  Macro F1           : %.4f\n' ...
         '  Weighted Precision : %.4f\n  Weighted Recall    : %.4f\n' ...
         '  Weighted F1        : %.4f\n  AUC (%s)           : %.4f\n\n'], ...
        tag, m.accuracy, m.macroPrecision, m.macroRecall, m.macroF1, ...
        m.weightedPrecision, m.weightedRecall, m.weightedF1, posClass, auc);
    blk('TRAINING SET',   mTrain, AUCtr);
    blk('VALIDATION SET', mVal,   AUCval);
    fclose(fid);
end
